[server]
maxUploadSize = 512
headless = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#004d73"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f5f7f8"
textColor = "#111111"
font = "sans serif"
